import fs from 'fs';
import path from 'path';

interface WordTimestamp {
  word: string;
  start: number;
  end: number;
  confidence: number;
  punctuated_word?: string;
}

function formatTime(seconds: number): string {
  if (seconds < 0) seconds = 0;
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100);

  const hStr = h.toString();
  const mStr = m.toString().padStart(2, '0');
  const sStr = s.toString().padStart(2, '0');
  const csStr = cs.toString().padStart(2, '0');

  return `${hStr}:${mStr}:${sStr}.${csStr}`;
}

export function generateAssFile(
  words: WordTimestamp[],
  startTime: number,
  endTime: number,
  outputPath: string
): void {
  // 1. Filter kata-kata yang masuk dalam durasi klip dan sesuaikan waktu mulainya
  const clipWords = words
    .filter((w) => w.start >= startTime && w.end <= endTime)
    .map((w) => ({
      text: w.punctuated_word || w.word,
      start: w.start - startTime,
      end: w.end - startTime,
    }));

  // 2. Kelompokkan kata-kata menjadi baris subtitle (dialogue groups)
  const groups: (typeof clipWords)[] = [];
  let currentGroup: typeof clipWords = [];
  const maxWords = 4;
  const maxChars = 25;
  const maxGap = 0.6; // Detik

  for (let i = 0; i < clipWords.length; i++) {
    const word = clipWords[i];
    currentGroup.push(word);

    const isLast = i === clipWords.length - 1;
    const nextWord = isLast ? null : clipWords[i + 1];
    
    const currentTextLength = currentGroup.map((w) => w.text).join(' ').length;
    const hasGap = nextWord ? nextWord.start - word.end > maxGap : false;
    const isGroupFull = currentGroup.length >= maxWords || currentTextLength >= maxChars;

    if (isLast || hasGap || isGroupFull) {
      groups.push(currentGroup);
      currentGroup = [];
    }
  }

  // 3. Bangun struktur file ASS dengan gaya tulisan CapCut
  // Menggunakan Liberation Sans (bold, besar, outline hitam tebal, Alignment=2 (tengah bawah) dipush agak ke atas)
  let assContent = `[Script Info]
Title: ClipForge Autogenerated Subtitles
ScriptType: v4.00+
PlayResX: 1280
PlayResY: 720
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Liberation Sans,38,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,2,10,10,120,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  // 4. Generate dialogue events dengan efek CapCut (aktif mewarnai kuning)
  for (const group of groups) {
    if (group.length === 0) continue;

    for (let wIdx = 0; wIdx < group.length; wIdx++) {
      const activeWord = group[wIdx];

      // Batasi waktu start & end agar transisi teks berjalan kontinyu
      const start = wIdx === 0 ? group[0].start : activeWord.start;
      const end = wIdx === group.length - 1 ? group[group.length - 1].end : group[wIdx + 1].start;

      // Rakit teks baris tersebut dengan mewarnai kuning hanya untuk kata yang aktif diucapkan
      const textParts = group.map((w, idx) => {
        const cleanText = w.text.replace(/[{}]/g, '');
        if (idx === wIdx) {
          return `{\\1c&H0000FFFF&}${cleanText}{\\1c&H00FFFFFF&}`;
        } else {
          return cleanText;
        }
      });

      const lineText = textParts.join(' ');
      assContent += `Dialogue: 0,${formatTime(start)},${formatTime(end)},Default,,0,0,0,,${lineText}\n`;
    }
  }

  fs.writeFileSync(outputPath, assContent, 'utf-8');
}
